### ISSUE TITLE
iOS app crashes when press the eye icon of note modal

### ISSUE THREAD

**Issue by kazup01** [BoostIO/boostnote-mobile#1]
iOS app crashes under the following state.

1, Open note modal (Press new post button / NOT editing a note)
2, Enter English randomly
3, Press eye icon while predictive conversion
4, App is crush

![sep-01-0029 19-50-52](https://user-images.githubusercontent.com/8602615/29966901-e9976124-8f4e-11e7-8fe9-1bf837aee2e2.gif)

**Comment by kohei-takata** [comment]
I added `autoCorrect={false}` to [this](https://github.com/BoostIO/boostnote-mobile/blob/master/MultilineTextInput.js#L45) and the bug was fixed.
