### ISSUE TITLE
Star the notes

### ISSUE THREAD

**Issue by kazup01** [BoostIO/boostnote-mobile#10]
<img width="573" alt="screen shot 0029-09-06 at 1 36 21 am" src="https://user-images.githubusercontent.com/8602615/30071990-d8cfd51c-92a3-11e7-9173-52629e03144f.png">

**Comment by robbawebba** [comment]
Is this feature still up for grabs? If so, I would love to help!

**Comment by kazup01** [comment]
This feature is not started yet. Please help!

**Comment by robbawebba** [comment]
@kazup01 After beginning development, I have a couple questions: 
* How should users be "starring" or "favoriting" these notes? I currently created the star icon as a toggle switch. To "favorite" the note, just tap the star-outline icon and it will mark the note as starred. This will also update the icon to be filled in.
* What is the function of the toggle switch in the picture above? To only display "starred" notes?

Thanks!

**Comment by kohei-takata** [comment]
Hi @robbawebba , thanks for your development!
- I think toggle switch is OK.
- Yes, its function is filtering notes.

Could you push your codes and create a PR?
Status of the PR will be work in progress.
It is OK.
I can check your codes earlier.

**Comment by robbawebba** [comment]
@kohei-takata Sorry for the delay! Work has been pretty busy lately so I've been behind on my personal development. I'll be sure to create an in-progress PR either today or tomorrow for the work I have so far.
