### ISSUE TITLE
Design issues in preferences window

### ISSUE THREAD

**Issue by kasperfm** [BoostIO/boostnote-mobile#114]
I'm using Boostnote v0.8.17 on Ubuntu 17.10 64bit, and found two issues.
- Strange black (check)box at the top of the preferences window.
- "Info: Release Note: v0.8.17" is too large for the sidebar.

![boostnote bug ubuntu 17 10](https://user-images.githubusercontent.com/849707/33393616-02bfd348-d540-11e7-97d7-b4e27b72f210.png)

**Comment by kohei-takata** [comment]
@kasperfm 
I will close this issue, because this repository is for boostnote-mobile.
Could you open this issue in [this](https://github.com/BoostIO/boostnote/issues) repository?
