### ISSUE TITLE
Android app crashes when you press "Dropbox" in menu

### ISSUE THREAD

**Issue by johnbeard** [BoostIO/boostnote-mobile#118]
I set up Boostnote mobile to connect to Dropbox, and it seems to have got past the auth stage (I put a key in). However, the list is still empty, and whenever I press "Dropbox" in the menu, the app immediately crashes. Just behind the menu, as it crashes, you can see a bit of a "Sign in to Dropbox" button.

This happens every time, it's never got further than that.

**Comment by Karrade7** [comment]
Same issue here. New install, got code, app continually crashes when clicking dropbox.

Going to clear cache, try again, then reinstall and try again.

**Comment by Karrade7** [comment]
Tried clearing cache. No chabge.
Cleared data and the it asked me to reset Dropbox. On going through the process again it crashed.
Then uninstalled and reinstalled installed.
I tried invalid tokens first and I got an error message without crashing. But once I used a valid token it crashed on submit.

**Comment by kazup01** [comment]
Hi guys, maybe I fixed this bug at https://github.com/BoostIO/boostnote-mobile/pull/122 .
v1.1.4 has already been submitted to google play, please wait a moment until app is updated.

If there is same bug at v1.1.4, feel free to talk to me. Thank you for report!

**Comment by Karrade7** [comment]
Thanks. I'll test when updated.

**Comment by pgbarletta** [comment]
Same problem here. 

Android 7.0
Motorola Droid Turbo 2
Boostnote 1.2.3
