### ISSUE TITLE
[Android] App crashed when I clicked on "send !" in dropbox code

### ISSUE THREAD

**Issue by theodugautier** [BoostIO/boostnote-mobile#120]
Hello,

When I clicked on "send !" after paste my dropbox code, app stopped. And when i tryed again, app stopped when i clicked on "dropbox" in menu.

Platform: Android
Android Version : 7.0
model: Huawei p8 lite 2017

**Comment by kazup01** [comment]
Hi @theodugautier , thanks for your report. I will investigate it.

**Comment by Cocas114** [comment]
Hello,

@kazup01 Thank you for being so active.

I don't know if it helps, but I also have the same problem on a different device

Platform: Android
Android Version: 5.0
Model: LG G3

**Comment by kazup01** [comment]
Hi @Cocas114 , thanks for your info ;)

**Comment by rmorabia** [comment]
Came here to report the same issue. Motorola G4, Android 7.0. It connected with Dropbox just fine in the first place (I got the email that said it did), and now even when I click on the Dropbox tab, it crashes every time.

**Comment by kazup01** [comment]
Thanks @rmorabia !

**Comment by kazup01** [comment]
Hi guys, maybe I fixed this bug at https://github.com/BoostIO/boostnote-mobile/pull/122 .
v1.1.4 has already been submitted to google play, please wait a moment until app is updated.

If there is same bug at v1.1.4, feel free to talk to me. Thank you for report!

**Comment by Cocas114** [comment]
Hi @kazup01,

It is working now, thanks!

**Comment by kazup01** [comment]
;)
