### ISSUE TITLE
Some links are broken in README.

### ISSUE THREAD

**Issue by myateke** [BoostIO/boostnote-mobile#129]
I followed the README and I found that the following links are broken. 
https://github.com/BoostIO/boostnote-mobile/blob/master/README.md#usage
- [Setting up React Native for Android](https://facebook.github.io/react-native/docs/android-setup.html#content)
- [Running app on Android Device](https://facebook.github.io/react-native/docs/running-on-device-android.html#content)
- [Running app on iOS Device](https://facebook.github.io/react-native/docs/running-on-device-ios.html#content)

**Comment by kazup01** [comment]
Fixed at #131.
Thank you for your report! @myateke

**Comment by myateke** [comment]
@Hastegan @kazup01 
Thanks a lot!
