### ISSUE TITLE
Bug - cannot update to v0.8.18

### ISSUE THREAD

**Issue by ilidnew** [BoostIO/boostnote-mobile#130]
Keep seeing this error when trying to update version. Also tried uninstalling and reinstalling the app.

![image](https://user-images.githubusercontent.com/6280944/33794329-55f55b78-dcca-11e7-8b2b-031a7a45ec21.png)

**Comment by kohei-takata** [comment]
Hi @ilidnew !
Thanks for your issue.

This issue is for Boostnote desktop, so I will close this issue.
Please check [this](https://github.com/BoostIO/Boostnote/issues/1239) issue.

**Comment by kazup01** [comment]
Hi @ilidnew , this bug has already fixed. Please reload your Boostnote!
Thanks for your waiting!
