### ISSUE TITLE
Cannot scroll with Dropbox view in Android app

### ISSUE THREAD

**Issue by fedomain** [BoostIO/boostnote-mobile#132]
Hi,

This might be related to #73.

But I am unable to scroll when I'm on the Dropbox view. 
I have 2 folders setup in my "/Apps/boostnote-mobile/notes" location.
Each folder have over 20 notes.
On the Android mobile app, I am unable to scroll in the Dropbox view to see all my notes.
I can see the folder and its notes loading but once all folders & files have been loaded I cannot scroll down to view the rest.

Some details about my setup:

Android version: 7.1.1 NMF26X
Phone Brand/Model: Xiaomi Mi 6
Boostnote app version: v1.1.5 (Android)

Thanks in advance.

**Comment by fedomain** [comment]
My apologies but I can't seem to add a label to this issue.
I mustn't have permission to do that.

**Comment by kazup01** [comment]
Hi @fedomain , thanks for your report! I will fix it tomorrow.

**Comment by fedomain** [comment]
@kazup01, thank you.
Boostnote is great btw. I use it everyday 👍

**Comment by kazup01** [comment]
@fedomain  Android v1.1.7 is out! Please check it 😄

**Comment by fedomain** [comment]
Yep, updated it and it works like a charm.
Thanks, @kazup01
