### ISSUE TITLE
Bold markdown having unexpected behaviour

### ISSUE THREAD

**Issue by Romsick** [BoostIO/boostnote-mobile#133]
## Explanation
When viewing (not editing) a Note that has bold statements, they behave in strange ways.
I mainly noticed this in lists. If you have a list item with the entire item in bold, the item becomes transparent or the boldness does not apply. This also happens having just one word of the list item marked as bold.

Lately I also noticed that for some reason sometimes a bold statement moves to another position when viewing the document, like above other previous lines (see images attached).

![boostnote-mobile_issue1](https://user-images.githubusercontent.com/34283607/33880269-69d89682-df31-11e7-9819-97d2e296a998.jpg)
![boostnote-mobile_issue1b](https://user-images.githubusercontent.com/34283607/33880273-6dc1c692-df31-11e7-99eb-e696ccd48ae5.jpg)

Tested only in iOS.

**Comment by kohei-takata** [comment]
Hi @Romsick ! Thanks for your issue!
I think this bug was fixed in the latest version.
Could you update boostnote in app store, and try again?
I will close this issue, but if you find something wrong, please comment.

**Comment by Romsick** [comment]
Fixed and working perfectly in this last update. Thank you!
