### ISSUE TITLE
Android  App Crashes When I Try To Do Anything

### ISSUE THREAD

**Issue by SarahLKatz** [BoostIO/boostnote-mobile#160]
The app is loading fine, but when i try to do anything, it crashes. I've tried opening existing notes, creating a new note, and accessing my Dropbox, and each action has the same result - the app crashes.

I'm using:
Samsung Galaxy S8+
Android Version 7.0
Boostnote Version 1.1.9 (latest version available in Play Store)

**Comment by aolwas** [comment]
Hi, 
I have the same behavior using Oneplus 5, Android 8.0.0 and Boostnote 1.1.9 freshly installed

**Comment by kriyss** [comment]
Hi, same here with boostnote v1.2.0

Android: 7.0
Phone: Samsung Galaxy S7
Boostnote: 1.2.0

**Comment by Henry78** [comment]
Android 8.0.0
Oneplus 3t
Boostnote 1.2.0 - new installation, i.e. 0 existing notes

**Comment by RoryDuncan** [comment]
Android 7.0, Note5,  boostnote v1.1.9 freshly installed.

Specifics for me: I can access the side menu and the icon links at the menu footer, but pressing the floating action button crashes the app.

**Comment by jwkicklighter** [comment]
Android 8.1.0
Pixel XL
Boostnote 1.2.0

The main screen loads, but I cannot access the Dropbox section of the app. It did display my synced notes when Dropbox was first connected, but trying to view them after the initial login now crashes.

**Comment by andy-williams** [comment]
Same on mine. Crashes when I try to create a new note or click the dropbox button.

Samsung Galaxy S7
Android 7.0

**Comment by RodrigoRosmaninho** [comment]
Hi, I'm having the same problems as the rest of the people who've commented on this issue.
I've tested this on 2 devices:

| Device          | Android Version   | App Version  |
|-----------------|:---------------:|:-----------------------------------:|
| Oneplus 3T | 8.0.0         | 1.1.9 / 1.2.0                            | 
| Samsung Galaxy Note 8.0 (Tablet)    | 4.4.2 | 1.2.0                             |

### Behaviour:
App force-quits, Android OS popup appears asking if I want to send feedback (I have).

### Causes:
Behavior occurs when the following actions are taken:

1. Clicking on the Floating Action Button to create a new note or in the 'Tab here to write something!' prompt
2. Clicking on any note in the dropbox tab (a note that was created on a PC, as creating one in the app is impossible) (*See note [1]*)
3. Clicking on the Dropbox button after the sync has been setup on a previous attempt (*See note [1]*)

#### Note [1]:
After installing the app, I click on the Dropbox button (as per the instructions of your Medium.com post multi-device sync) and successfully log in to my account. 
A list of the posts I've previously created on my computer appears. 

However, if I click on one of the notes, a screen (where I suppose the note body should be) appears for a split second and then the app force-quits.

Furthermore, if I start the app again and click on the dropbox button the app force-quits again and doesn't let me see the list of notes on my dropbox. The only way I can do that is by deleting all app data in the Android app settings then opening the app again.

### Logcat:
(Taken from my Oneplus 3T - Android 8.0.0 - App v1.2.0)
#### For cause number 1:
What follows is the error that appears in the logcat if I click on the 'new note' FAB (in the 'All Notes' tab):

```
--------- beginning of crash
01-05 01:12:10.564 24985 25013 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
01-05 01:12:10.564 24985 25013 E AndroidRuntime: Process: io.boostnote, PID: 24985
01-05 01:12:10.564 24985 25013 E AndroidRuntime: java.lang.IllegalArgumentException: unexpected url: app_resource_noteinputsupporticons_iconhead
01-05 01:12:10.564 24985 25013 E AndroidRuntime: 	at okhttp3.Request$Builder.url(Request.java:142)
01-05 01:12:10.564 24985 25013 E AndroidRuntime: 	at com.facebook.react.modules.network.NetworkingModule.sendRequest(NetworkingModule.java:171)
01-05 01:12:10.564 24985 25013 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-05 01:12:10.564 24985 25013 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
01-05 01:12:10.564 24985 25013 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
01-05 01:12:10.564 24985 25013 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-05 01:12:10.564 24985 25013 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
01-05 01:12:10.564 24985 25013 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
01-05 01:12:10.564 24985 25013 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
01-05 01:12:10.564 24985 25013 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-05 01:12:10.564 24985 25013 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
01-05 01:12:10.564 24985 25013 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
01-05 01:12:10.564 24985 25013 D AppTracker: App Event: crash
01-05 01:12:10.597 24985 24985 D AppTracker: App Event: stop
01-05 01:12:10.613 24985 24985 E DeviceManagerUtil: RunningAppProcessInfo is null
01-05 01:12:10.614 24985 24985 E DeviceManagerUtil: RunningAppProcessInfo is null
01-05 01:12:11.040 24985 24985 D ReactNative: ReactInstanceManager.detachViewFromInstance()
```

#### For cause number 2:
What follows is the error that appears in the logcat if I click on any note on the list of notes in the dropbox tab (after clean install):

```
--------- beginning of crash
01-05 01:51:17.006 28295 28323 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
01-05 01:51:17.006 28295 28323 E AndroidRuntime: Process: io.boostnote, PID: 28295
01-05 01:51:17.006 28295 28323 E AndroidRuntime: java.lang.IllegalArgumentException: unexpected url: app_resource_noteinputsupporticons_iconhead
01-05 01:51:17.006 28295 28323 E AndroidRuntime: 	at okhttp3.Request$Builder.url(Request.java:142)
01-05 01:51:17.006 28295 28323 E AndroidRuntime: 	at com.facebook.react.modules.network.NetworkingModule.sendRequest(NetworkingModule.java:171)
01-05 01:51:17.006 28295 28323 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-05 01:51:17.006 28295 28323 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
01-05 01:51:17.006 28295 28323 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
01-05 01:51:17.006 28295 28323 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-05 01:51:17.006 28295 28323 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
01-05 01:51:17.006 28295 28323 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
01-05 01:51:17.006 28295 28323 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
01-05 01:51:17.006 28295 28323 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-05 01:51:17.006 28295 28323 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
01-05 01:51:17.006 28295 28323 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
01-05 01:51:17.006 28295 28323 D AppTracker: App Event: crash
01-05 01:51:17.027 28295 28295 D AppTracker: App Event: stop
01-05 01:51:17.033 28295 28295 E DeviceManagerUtil: RunningAppProcessInfo is null
01-05 01:51:17.034 28295 28295 E DeviceManagerUtil: RunningAppProcessInfo is null
01-05 01:51:17.668 28295 28295 D ReactNative: ReactInstanceManager.detachViewFromInstance()
```

#### Note:
From what I can tell, both errors (1 and 2) are (almost) identical.
I don't know any React, but is the view/activity that gets called when the 'new note' button is clicked the same as when a pre-existing note is clicked?
Could it be there's an error somewhere within that view/activity or the process of calling it?

#### For cause number 3:
What follows is the error that appears in the logcat if I click on the 'dropbox' button after the error of cause number 2 has already happened:

```
--------- beginning of crash
01-05 01:59:11.799 29637 29662 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
01-05 01:59:11.799 29637 29662 E AndroidRuntime: Process: io.boostnote, PID: 29637
01-05 01:59:11.799 29637 29662 E AndroidRuntime: com.facebook.react.uimanager.IllegalViewOperationException: Trying to set local data for view with unknown tag: 96
01-05 01:59:11.799 29637 29662 E AndroidRuntime: 	at com.facebook.react.uimanager.UIImplementation.setViewLocalData(UIImplementation.java:246)
01-05 01:59:11.799 29637 29662 E AndroidRuntime: 	at com.facebook.react.uimanager.UIManagerModule$3.runGuarded(UIManagerModule.java:348)
01-05 01:59:11.799 29637 29662 E AndroidRuntime: 	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:21)
01-05 01:59:11.799 29637 29662 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
01-05 01:59:11.799 29637 29662 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
01-05 01:59:11.799 29637 29662 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
01-05 01:59:11.799 29637 29662 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-05 01:59:11.799 29637 29662 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
01-05 01:59:11.799 29637 29662 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
01-05 01:59:11.799 29637 29662 D AppTracker: App Event: crash
01-05 01:59:11.809 29637 29637 I zygote  : Deoptimizing void com.facebook.react.uimanager.events.EventDispatcher.moveStagedEventsToDispatchQueue() due to JIT inline cache
01-05 01:59:11.816 29637 29637 I zygote  : Deoptimizing void com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(int, com.facebook.react.uimanager.ReactStylesDiffMap) due to JIT inline cache
01-05 01:59:11.830 29637 29637 D AppTracker: App Event: stop
01-05 01:59:11.831 29637 29637 E DeviceManagerUtil: RunningAppProcessInfo is null
01-05 01:59:11.832 29637 29637 E DeviceManagerUtil: RunningAppProcessInfo is null
01-05 01:59:12.322 29637 29637 D ReactNative: ReactInstanceManager.detachViewFromInstance()
```


---
Attached are 2 files containing the full logcat output for errors 2 and 3:
[log2.txt](https://github.com/BoostIO/boostnote-mobile/files/1605314/log2.txt)
[log3.txt](https://github.com/BoostIO/boostnote-mobile/files/1605315/log3.txt)

I hope I've helped and that your team can fix these errors.
Good luck!




@kazup01 @kohei-takata @sosukesuzuki

**Comment by domcorvasce** [comment]
I had the same problem.

Device: Xiaomi Redmi Note 4

Android: 7.0

ROM: MIUI 8.1.4

The app crashes when I try to create a note clicking on the float button.

Here's the report:

![Report](https://camo.githubusercontent.com/818230120af43b3cc3e1340c9889d9d74e3b029f/68747470733a2f2f7331382e706f7374696d672e6f72672f7668763530767570352f53637265656e73686f745f323031382d30312d30352d30382d30342d35392d3633335f636f6d2e6d6975692e6275677265706f72742e706e67)

**Comment by RodrigoRosmaninho** [comment]
Thanks for the update but at least in my device the problem I called number 3 in my comment above is still there.

I can't click on the Dropbox button after the first time I do it

**Comment by killerYe** [comment]
I have the same problem.

|Phone|Version|
|:--:|:--:|
|vivo x9|android 7.0|

**Comment by andreinl** [comment]
The same problem on iPad 2 and Android phone
