### ISSUE TITLE
Crashes when clicking plus button when connecting Dropbox

### ISSUE THREAD

**Issue by mslourens** [BoostIO/boostnote-mobile#177]
To reproduce this issue, follow these steps (for me it always happens, on Android 7.1.2 Nexus 5):

- click the Dropbox button in the menu (there is no Dropbox connection yet)
- notice the big green plus button is still there
- click the plus for creating a new note.
- the app crashes.

**Expected behavior**: 
When connecting Dropbox the floating button should be hidden, because it has no function in the connecting process. Or otherwise the connection screen should disappear and a new note should be created.

**Actual behavior**:
The app crashes.

**Comment by sosukesuzuki** [comment]
fix from #180
