### ISSUE TITLE
iPad version?

### ISSUE THREAD

**Issue by dpo** [BoostIO/boostnote-mobile#24]
Very excited that Boostnote is making it to mobile platforms! I wonder if an iPad version is in the works? The iOS version seems to be for iPhone, with fixed orientation.

Thanks for a great note app!

**Comment by kazup01** [comment]
Thanks for @dpo your trying! iPad app is under waiting for review👍
<img width="669" alt="screen shot 0029-09-24 at 12 03 43 pm" src="https://user-images.githubusercontent.com/8602615/30779077-a495d2de-a120-11e7-81ba-bd896bf6e9b8.png">

**Comment by dpo** [comment]
Really looking forward!!!

**Comment by kazup01** [comment]
iPad app is coming!
![s__3481602](https://user-images.githubusercontent.com/8602615/30841837-383403c8-a2b9-11e7-8572-d3f43895f24b.jpg)

**Comment by kazup01** [comment]
Enjoy
