### ISSUE TITLE
No Scrolling in Preview Mode

### ISSUE THREAD

**Issue by AlwaysKamin** [BoostIO/boostnote-mobile#56]
It seems that within the iOS app on my iPhone 7+ there is no scrolling in the preview pane. So currently while editing a note you can simply scroll like normal. But when you enter into the preview / viewing pane you can no longer scroll with one finger. This happens within the local files as well as the drop box files. When on the physical device you can engage the scrolling with two fingers for some reason, and then within the simulator in xcode you can not get it to scroll with input.

---
# From the simulator:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/8315826/31747930-d68efee8-b43d-11e7-9e2b-daa4bc4ef0ef.gif)

**Comment by kohei-takata** [comment]
Hi @AlwaysKamin !
Thanks for your opening issue!
It occurs after merging #44, I think.
I will fix this.

**Comment by joanvalis** [comment]
The same problem is present in the Android 1.0.6 version.

**Comment by kazup01** [comment]
I fixed it at #107. Thank you for waiting! @AlwaysKamin @joanvalis
