### ISSUE TITLE
! Exclamation mark causes line break in code block

### ISSUE THREAD

**Issue by drmason13** [BoostIO/boostnote-mobile#68]
Just installed on android 7.1.2 today.

Wrote a code block:

```
println!("hello world");
```

Which rendered as (using the preview):

println
!("hello world");

Experimenting a little; it is clear that every ! is printed on a new line when previewed.

Has an exception been made to cause this behaviour?

Personally it is very unhelpful. For me, expected behaviour would be: never add line breaks in a code block: all characters should be rendered as is - simple as that.

**Comment by kazup01** [comment]
The feature of Markdown render we are using is still incomplete. We will make this library ourselves and plan to release it in open source.
I'm apologize for any inconvenience, please wait for a while.

**Comment by kohei-takata** [comment]
Hi @drmason13 !
I think this bug was fixed in the latest version.
Could you update boostnote in google play store, and try again?
I will close this issue, but if you find something wrong, please comment.
