### ISSUE TITLE
Text in Quotes not being rendered at all

### ISSUE THREAD

**Issue by boonhui-lai** [BoostIO/boostnote-mobile#69]
Any text in quotes like so: `hello world` is not being rendered.

**Comment by kazup01** [comment]
The feature of Markdown render we are using is still incomplete. We will make this library ourselves and plan to release it in open source.
Thank you for your waiting!

**Comment by kohei-takata** [comment]
Hi @boonhui-lai !
I think this bug was fixed in the latest version.
Could you update boostnote in app store or google play store, and try again?
I will close this issue, but if you find something wrong, please comment.

**Comment by boonhui-lai** [comment]
Yup it has been resolved. Thanks
