### ISSUE TITLE
Editing the DropBox-synced notes

### ISSUE THREAD

**Issue by dayfuaim** [BoostIO/boostnote-mobile#78]
It should be able to edit my synced notes, not only view them.

**Comment by kazup01** [comment]
Coming soon. Thank you for your waiting!

**Comment by dayfuaim** [comment]
Woah!
"How fast is your sword!" :)
So I wait impatiently.

**Comment by kazup01** [comment]
👍

**Comment by enriro** [comment]
I would also like this feature.

Great app

**Comment by BoGGoG** [comment]
Came here to ask for the same thing =)
Also if I am not mistaken a note created on iOS doesn't sync to dropbox, since one can only create a note in the local folder?

**Comment by kazup01** [comment]
Hi guys, this feature was released at iOS v1.1.0 and Android v1.0.9. 
The syncing manual is here. https://medium.com/boostnote/boostnote-mobile-how-to-synchronize-with-dropbox-95d845581eea

**Comment by kazup01** [comment]
Enjoy Boostnote :)
