### ISSUE TITLE
Markdown input assistance.

### ISSUE THREAD

**Issue by kazup01** [BoostIO/boostnote-mobile#8]
Like below image.
<img width="386" alt="screen shot 0029-09-06 at 1 32 25 am" src="https://user-images.githubusercontent.com/8602615/30071835-486c9992-92a3-11e7-932d-a106d1db91a2.png">

**Comment by kazup01** [comment]
Available for Android. #17

**Comment by kohei-takata** [comment]
Now that this feature is available in iOS too.
So I close this issue.
