### ISSUE TITLE
Notes doesn't scroll down in Preview mode

### ISSUE THREAD

**Issue by enriro** [BoostIO/boostnote-mobile#80]
Notes doesn't scroll down in Preview mode iOS 10.3.3, I can scroll them only in Edit mode

**Comment by kohei-takata** [comment]
Hi @enriro !
It is a bug, and I will fix!

**Comment by kazup01** [comment]
Hi @enriro , I fixed it at #107. I will update mobile app at soon, thanks for your waiting!
