### ISSUE TITLE
It would be great to be able to copy or move files on iOS 

### ISSUE THREAD

**Issue by enriro** [BoostIO/boostnote-mobile#85]
It would be great to be able to copy and move notes on iOS between Dropbox synced and locally stored. And also be able to delete and modify Dropbox notes of course.

**Comment by kohei-takata** [comment]
I will not implement the feature, because we can copy/paste the note.

> And also be able to delete and modify Dropbox notes of course.

This feature will be implemented.

**Comment by enriro** [comment]
> I will not implement the feature, because we can copy/paste the note.

How? Dropbox notes even does not have a drop down menu or something. I can only view them **without even scrolling by the way**

**Comment by kohei-takata** [comment]
Its code have been marged.
It will be released sooner as sooner
