### ISSUE TITLE
15.11.2017 release doesn't show notes from dropbox 

### ISSUE THREAD

**Issue by enriro** [BoostIO/boostnote-mobile#96]
15.11.2017 release doesn't show notes from dropbox. App reinstalling and relinking Dropbox doesn't help iOS 10.3.3

Dropbox folder boostnote-mobile exists and contains old notes

**Comment by kazup01** [comment]
HI @enriro, sorry for the inconvenience.
This is bug,so we already fixed it and sent for Apple’s examination.
Wait a moment.

**Comment by kazup01** [comment]
Hi @enriro , thank you for waiting. This problem was fixed at iOS v1.1.0 and Android V1.0.9.
If bug still occurring, feel free to tell me.
